### ISSUE TITLE
Compatibility issue with SQLAlchemy 1.4

### ISSUE THREAD

**Issue by dsilletti** [singingwolfboy/flask-dance#349]
After SQLAlchemy upgrade to v1.4 I get this exception:

`ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query'`

**Comment by singingwolfboy** [comment]
Thanks! This seems like a problem with `sqlalchemy-utils`. However, we don't actually need it anymore, so I removed that dependency here: https://github.com/singingwolfboy/flask-dance/pull/350

I'll give it a few days to see if we can get https://github.com/singingwolfboy/flask-dance/pull/348 to merge as well. Once it's merged, or if I determine that it probably won't merge soon, then I'll release a new version of Flask-Dance, which should be compatible with SQLAlchemy 1.4.

**Comment by singingwolfboy** [comment]
Flask-Dance 4.0.0 is now released! https://pypi.org/project/Flask-Dance/4.0.0/ This should be compatible with SQLAlchemy 1.4.

**Comment by dsilletti** [comment]
@singingwolfboy excellent! I just rebuilt my app using Flask-Dance 4.0.0 and I can confirm it's working with no issues with SQLAlchemy 1.4.
